// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbzaoioqtvknftymrqao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiemFvaW9xdHZrbmZ0eW1ycWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjU2NzYsImV4cCI6MjA3MzAwMTY3Nn0.8peAPSmMC9nrBJNb7dja0XzwpSeuMRcLGzQz3P-QEqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});